name: SDK Test

on:
  push:
    branches: [ "github-actions-setup" ]
  pull_request:
    branches: [ "github-actions-setup" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.5", "3.6", "3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -e .
      - name: Install pytest
        run: pip install pytest
      - name: Run the tests
        env:
          SHIPPO_API_KEY: ${{ secrets.SHIPPO_TEST_KEY }}
        run: pytest -v
